name: Run and Test Code on Push to Test Branch

on:
  push:
    branches:
      - test

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment
      run: |
        lsb_release -a
        sudo apt update
        sudo apt install -y gcc-11 g++-11 make
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        gcc --version
        g++ --version

    - name: Make clean
      run: make clean

    - name: Build project
      run: make

    - name: Execute program and remove comments
      run: |
        printf '1\n' | ./stage1exe "Test Cases/t2.txt"
      shell: bash

    - name: Compare output
      run: |
        diff commentremove.txt "Test Cases/commentremoval_t2.txt"
