name: Run and Test Code on Push to Test Branch

on:
  push:
    branches:
      - test

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC
      uses: actions/setup-cpp@v2
      with:
        gcc-version: '11.4.0'
        architecture: x64

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Make clean
      run: make clean

    - name: Build project
      run: make

    - name: Execute program and remove comments
      run: |
        printf '1\n' | ./stage1exe "Test Cases/t2.txt"
      shell: bash

    - name: Compare output
      run: |
        diff commentremove.txt "Test Cases/commentremoval_t2.txt"
